suppressPackageStartupMessages({
  library(reticulate)
  library(dplyr)
  library(glue)
})
use_condaenv("challenge_env", required = TRUE)
cu <- import("challengeutils")
syn <- import("synapseclient")
synObj <- syn$Synapse()
synObj$login(silent = TRUE)
